[package]
name = "sciml-rs"
version = "0.1.0-dev"
authors = ["The sciml-rs developers"]
edition = "2024"
description = "Scientific machine learning tools in Rust"
license = "MIT / Apache-2.0"
homepage = "https://codeberg.com.com/sciml-rs/sciml-rs"
repository = "https://codeberg.org/sciml-rs/sciml-rs.git"
readme = "README.md"
keywords = ["neural operators"]
categories = ["scientific machine learning"]

[lib]
name = "sciml_rs"

[[example]]
name = "train_burgers"
path = "examples/train/burgers.rs"

[[example]]
name = "train_darcy"
path = "examples/train/darcy.rs"

[[example]]
name = "predict_burgers"
path = "examples/predict/burgers.rs"

[[example]]
name = "predict_darcy"
path = "examples/predict/darcy.rs"

[dependencies]
# burn = { version = "0.22.0-pre.3", features = ["autodiff", "flex", "store", "train"] }
# burn = { version = "0.22.0-pre.3", features = ["autodiff", "wgpu", "store", "train"] }
burn = { version = "0.22.0-pre.3", features = ["autodiff", "metal", "store", "train"] }
ndarray = "0.17"
ndarray-npy = "0.10"
matfile = "0.5"
gnuplot = "0.0.46"

[dev-dependencies]
approx = { version = "0.5", features = ["num-complex"] }

[target.'cfg(target_os= "macos")'.dev-dependencies]

[target.'cfg(target_os= "linux")'.dev-dependencies]