name: 🧪 run-examples

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-examples:
    name: run-examples
    runs-on: codeberg-small-lazy
    steps:
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@v1

      - uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install cargo-templated-examples
        run: cargo install cargo-templated-examples

      - name: Check if dependencies are up-to-date
        run: cargo templated-examples NPROCESSES 3
