name: 🧪 run-examples

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-examples:
    name: run-examples
    runs-on: codeberg-medium
    steps:
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install cargo-templated-examples
        run: cargo install cargo-templated-examples

      - name: Fix PLIRON version to 0.17.0
        run: |
          cargo update -p pliron --precise 0.17.0
          cargo update -p pliron-llvm --precise 0.17.0

      # - name: Run examples
      #   run: cargo templated-examples
