name: 🧪 run-tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests-rust:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable

      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      # - name: Add universe repository
      #   run: sudo add-apt-repository universe

      # - name: Update package list
      #   run: sudo apt-get update

      # - name: Install libclang
      #   run: sudo apt-get install -y libclang-dev

      # - name: Install CMake
      #   run: sudo apt-get install -y cmake

      # - name: Install FFTW
      #   run: sudo apt-get install -y libfftw3-dev

      # - name: Install Blas
      #   run: sudo apt-get install -y libopenblas-dev

      # - name: Install MPI
      #   run: sudo apt-get install -y openmpi-bin libopenmpi-dev

      - name: Run unit tests
        run: cargo test 

      - name: Build docs
        run: cargo doc --no-deps

  style-checks-rust:
      name: style-checks
      runs-on: ubuntu-latest
      steps:
        - name: Install Rust
          uses: dtolnay/rust-toolchain@v1
          with:
            components: clippy, rustfmt
            toolchain: stable
  
        - uses: actions/checkout@v6

        - uses: Swatinem/rust-cache@v2
  
        # - name: Add universe repository
        #   run: sudo add-apt-repository universe
  
        # - name: Update package list
        #   run: sudo apt-get update
  
        # - name: Install libclang
        #   run: sudo apt-get install -y libclang-dev
  
        # - name: Install CMake
        #   run: sudo apt-get install -y cmake
  
        # - name: Install FFTW
        #   run: sudo apt-get install -y libfftw3-dev
  
        # - name: Install Blas
        #   run: sudo apt-get install -y libopenblas-dev
  
        # - name: Install MPI
        #   run: sudo apt-get install -y openmpi-bin libopenmpi-dev
  
        - name: Format
          run: cargo fmt -- --check
  
        - name: Clippy
          run: |
            cargo clippy --no-deps -- -D warnings
            cargo clippy --no-deps --examples -- -D warnings

  run-tests-chebyshev:
    name: run-tests-chebyshev
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable

      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      - name: Install OpenBLAS
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - name: Clippy (chebyshev)
        run: cargo clippy --no-deps --features chebyshev --all-targets -- -D warnings

      - name: Run tests (chebyshev)
        run: cargo test --features chebyshev
